### PR TITLE
Stripe successfully implemented

### PR DESCRIPTION
**Pull request by bearcanrun**
I'm super excited, because I really needed Stripe working for my project use.

So it's kind of hacky, but we had to go around webpack. Basically used `meteorhacks:npm` to bring in Stripe dep.
Remember to set your Stripe secret key in settings.
Note: You may have to run  node dev twice, becuase meteorhacks:npm builds its own node modules in Meteor root.

Confirmed plan added in Stripe panel. 

Todo:
Make the `id` in Stripe.plans.create dynamic. Otherwise you can only create one plan right now.
Not sure if we still need `Meteor.isServer` check. . . didn't test.

### CODE REVIEW

**Comment by gdub01** [comment]
Thanks! That was a creative idea. The id can just be swapped with the var docId (created a couple lines above which is the newly created planId.)

I'm not super keen on getting a second version of web pack running if possible. I'm going to try to find another way to get it running.

**Comment by bearcanrun** [comment]
What do you mean by second version of webpack? [meteorhacks: npm](https://github.com/meteorhacks/npm) is pretty lightweight and loads Stripe properly onto the Server side

[Webpack's loaders break that pattern.](https://github.com/stripe/stripe-node/issues/139)

**Comment by bearcanrun** [comment]
Ok, duh, using stripe via meteorhacks:npm would still break the security pattern because whatever it does would of course get  bundled in by webpack. I'm still trying to wrap my head around all these new things. . .

**Comment by gdub01** [comment]
Hey man, I just pushed another option to implement stripe to master.. and
that's with mr.galaxy's package. What do you think of that option?

**Comment by bearcanrun** [comment]
Hey that's great. I had tried Mr. Galaxy's package, and it wasn't working. It actually loads Stripe the same way, meteorhacks:npm is just a more generic npm loader. So I'll play with it again and probably find out it was just me. 

I tried to ask about the security implications of using Stripe via webpack on the meteor forums, but no responses.

**Pull request closed without merging**
